### ISSUE TITLE
模型文件

### ISSUE THREAD

**Issue by KyleWang-Hunter** [GaoKangYu/Seal-OCR-For-BLAR#1]
请问下，训练好的h5模型能提供吗？

**Comment by GaoKangYu** [comment]
你好，CRAFT模型权重即为作者提供的预训练权重。
TPS模型权重下载地址为：链接：https://pan.baidu.com/s/1YDRVt82JtIQCfXNHxM4BZw 提取码：z81d

**Comment by KyleWang-Hunter** [comment]
谢谢解答

**Comment by KyleWang-Hunter** [comment]
> 你好，CRAFT模型权重即为作者提供的预训练权重。 TPS模型权重下载地址为：链接：https://pan.baidu.com/s/1YDRVt82JtIQCfXNHxM4BZw 提取码：z81d

请问  从pdf文件中提取印章部分的代码能提供下吗？

**Comment by GaoKangYu** [comment]
你好，抱歉忘记回复了。

从PDF提取印章直接采用了目标检测方法，自行标注数据训练一个轻量级模型即可，可使用YOLO系列模型。
